INSERT INTO CLASSE VALUES('mammifere');
INSERT INTO CLASSE VALUES('reptile');
INSERT INTO CLASSE VALUES('poisson');
INSERT INTO CLASSE VALUES('oiseau');
INSERT INTO CLASSE VALUES('insecte');
INSERT INTO CLASSE VALUES('arachnide');