db.Clinique.insert(
{
	"client":[
		{
			"nom":"Jugnot",
			"prenom":"Gerard",
			"date_naissance":"1955-12-04",
			"adresse":"255 avenue foch, Paris",
			"telephone":0745869621,
			"animaux":[
				{
					"nom":"Griffon",
					"dernier_poids_mesure":"25.3",
					"derniere_taille_mesure":"1.058",
					"annee":2012,
					"espece":{
							"nom":"chien",
							"classe_especes_animales":"mammifere",
							"medicaments_autorisés":[
								{
									"molecule":"rinoxolone"
								}
							]
					}
					"traitement":[
						{
							"nom":"traitement foie",
							"debut_date":"2015-06-06"
							"medicaments":[
								{
									"molecule":"rinoxolone",
									"description":"debloque le foie"
								}
							]
						}
					]
				}
			]
		},
		{
			"nom":"Cotillard",
			"prenom":"Marion",
			"date_naissance":"1985-04-12",
			"adresse":"41 rue de neuilly, Nanterre",
			"telephone":0256368596,
			"animaux":[
				{
					"nom":"Myrtille",
					"dernier_poids_mesure":"2.4",
					"derniere_taille_mesure":".268",
					"annee":2014,
					"espece":{
							"nom":"truite",
							"classe_especes_animales":"poisson",
							"medicaments_autorisés":[
								{
									"molecule":"bronchioture"
								}
							]
					}
					"traitement":[
						{
							"nom":"traitement bronchie",
							"debut_date":"2015-06-08"
							"medicaments":[
								{
									"molecule":"bronchioture",
									"description":"nettoie les bronchies"
								}
							]
						}
					]
				}
			]
		}
		
	]
}
)
